services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: summarize_db_container
    environment:
      - 'POSTGRES_DB=summarize_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1111'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: