services:
  # 1. Database (PGVector)
  postgres:
    image: 'pgvector/pgvector:pg16'
    container_name: summarize_db_container
    environment:
      - 'POSTGRES_DB=summarize_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1111'
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d summarize_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 2. Redis
  redis:
    image: 'redis:latest'
    container_name: summarize_redis_container
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  springboot:
    build: .
    container_name: summarize_backend
    ports:
      - "8085:8085"
    environment:
      PORT: ${PORT}

      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

      FASTAPI_URL: ${FASTAPI_URL}
      UPLOAD_MAX_SIZE: ${UPLOAD_MAX_SIZE}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
volumes:
  postgres_data: