services:
  springboot:
    build: .
    container_name: summarize_backend
    ports:
      - "8085:8085"
    environment:
      PORT: ${PORT}

      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${SPRING_REDIS_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}

      BREVO_API_KEY: ${BREVO_API_KEY}
      MAIL_FROM: ${MAIL_FROM}

      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

      FASTAPI_URL: ${FASTAPI_URL}
      UPLOAD_MAX_SIZE: ${UPLOAD_MAX_SIZE}

    restart: always