# Giai đoạn 1: Build file JAR bằng Maven
FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app
# Copy file pom.xml và source code vào để build
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Giai đoạn 2: Chạy ứng dụng với JRE nhẹ
FROM eclipse-temurin:21-jre
WORKDIR /app

# Copy file jar từ giai đoạn build sang
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8085

ENTRYPOINT ["java", "-jar", "app.jar"]